### ISSUE TITLE
`FOOTPRINT` object has no attribute `HasProperty`

### ISSUE THREAD

**Issue by misteraddons** [bennymeg/JLC-Plugin-for-KiCad#122] opened 2024-02-23 23:57 UTC
Freshly installed on KiCad 8 MacOS (perhaps it's not yet supported). I haven't used this plugin before but installed it using the official plugin manager.
Steps to reproduce:
1) Click the Fabrication Toolkit button
2) Click Generate
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/51079966/358becd5-ed88-4e80-814c-5f6a73620e08)
3) Error message
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/51079966/e1837846-65e9-4685-a62b-7a2a680380ad)

**Comment by revk** [comment] 2024-02-24 07:30
Doing the same for me. Obviously an 8.0 issue.

The extra option screen is a nuisance, can we lose that somehow?

Anything we can do to help?

**Comment by tcurdt** [comment] 2024-02-24 12:14
Seems like the API has changed.

  https://github.com/bennymeg/JLC-Plugin-for-KiCad/commit/8dc0e8a440d2cefc9c1b96be43f5494eeb7fa9a3

and the required change was already merged.

  https://github.com/bennymeg/JLC-Plugin-for-KiCad/pull/109

Maybe we are just not getting the most recent version?

**Comment by tcurdt** [comment] 2024-02-24 12:18
Yes, 3.1.0 does not have the fix yet. So it needs a new release.

https://github.com/bennymeg/JLC-Plugin-for-KiCad/compare/3.1.0...master

Work around could be to install master for now.

**Comment by revk** [comment] 2024-02-24 12:34
I'll try that.

**Comment by revk** [comment] 2024-02-24 12:45
I can confirm the master works, is there any way to remove the asking the option at the start?  I can't see quite what to comment out to do that.

**Comment by tcurdt** [comment] 2024-02-24 12:57
> I can confirm the master works, is there any way to remove the asking the option at the start? I can't see quite what to comment out to do that.

I assume you would need to replace [this here](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/master/plugins/plugin.py#L94) with `ProcessThread(self, dict())`

But that's just from briefly looking at the code.

**Comment by revk** [comment] 2024-02-24 13:05
Yeh, I got as far as

```
        options = dict()
        options[EXCLUDE_DNP_OPT] = False;
        ProcessThread(self, options)
```

And no joy.

**Comment by revk** [comment] 2024-02-24 13:26
Unrelated, but a part that previously had a position offset of 5,0 now needs 0,2.61

I have no clue why!

**Comment by tcurdt** [comment] 2024-02-24 13:38
> Yeh, I got as far as
> 
> ```
>         options = dict()
>         options[EXCLUDE_DNP_OPT] = False;
>         ProcessThread(self, options)
> ```
> 
> And no joy.

Ah... seems it does need the dialog.

Check out an older version:

https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/2.3.0/plugins/plugin.py

**Comment by bennymeg** [comment] 2024-02-24 16:33
> The extra option screen is a nuisance, can we lose that somehow?

I have added it due to a request to add export options (Currently for dnp components). 

> Unrelated, but a part that previously had a position offset of 5,0 now needs 0,2.61
I have no clue why!

The positioning algorithm had been improved substantially, and a few breaking changes has been introduced to v4 of the plugin.
Read more in the upcoming official release.

---

Duplicate of (#109, #112, #114, #119).

**Closed by bennymeg** 2024-02-24 16:33 UTC
